language: cpp

compiler:
    - gcc
    - clang

env:
    global:
        - MONGO_REPO="http://repo.mongodb.com/apt/ubuntu"
        - REPO_TYPE="precise/mongodb-enterprise/stable multiverse"
        - SOURCES_LOC="/etc/apt/sources.list.d/mongodb-enterprise.list"
        - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
        - CMAKE_VERSION="cmake-3.2.3-Linux-x86_64"
        - CMAKE_BINARY="${CMAKE_VERSION}/bin/cmake"
        - CDRIVER_VERSION="1.3.5"

    matrix:
        - CONFIG=Release
        - CONFIG=Debug

# Setup required repositories before installation
before_install:
    # Add the modern toolchain repositories (llvm repo depends on ubunut-toolchain-r + gcc)
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

    # Get the latest CMake
    - curl -O https://cmake.org/files/v3.2/${CMAKE_VERSION}.tar.gz

    # MongoDB Enterprise Edition, latest stable version
    - sudo apt-key adv --keyserver ${KEY_SERVER} --recv 7F0CEB10
    - sudo apt-key adv --keyserver ${KEY_SERVER} --recv D68FA50FEA312927
    - echo "deb ${MONGO_REPO} ${REPO_TYPE}" | sudo tee ${SOURCES_LOC}

    # CMake
    - sudo add-apt-repository --yes ppa:kalakris/cmake

    # Update all the repositories
    - sudo apt-get update -qq

    # Mongo C Driver
    - curl -O -L https://github.com/mongodb/mongo-c-driver/releases/download/${CDRIVER_VERSION}/mongo-c-driver-${CDRIVER_VERSION}.tar.gz

    # Mongo C++ Driver
    - git clone -b 'master' --single-branch https://github.com/mongodb/mongo-cxx-driver.git

install:
    # GCC
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-6; export CXX="g++-6"; export CC="gcc-6"; fi

    # Clang
    - if [ "$CXX" == "clang++" ]; then wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -; sudo apt-get install --allow-unauthenticated -qq clang-3.8; export CXX="clang++-3.8"; export CC="clang-3.8"; fi

    # CMake
    - tar -zxf ${CMAKE_VERSION}.tar.gz -C build

    # Install MongoDB Enterprise
    - sudo apt-get install mongodb-enterprise-server

    # Install CMake (Versions lower than 2.8.8 do not support object libraries)
    - sudo apt-get install cmake

    # Prepare pkg-config path
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/home/travis/install/lib/pkgconfig/

    # Install Mongo C Driver
    - tar -zxf mongo-c-driver-${CDRIVER_VERSION}.tar.gz
    - pushd mongo-c-driver-${CDRIVER_VERSION}; ./configure --prefix=/home/travis/install; make; sudo make install; popd;

    # Install Mongo C++ Driver
    - pushd mongo-cxx-driver/build; ../../build/${CMAKE_BINARY} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/travis/install/ ..; make; sudo make install; popd; 

before_script:
    - $CC --version
    - $CXX --version

    # Build the odm and the tests
    - cd build
    - ${CMAKE_BINARY} -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_MODULE_PATH=/home/travis/build/mongodb/mongo-cxx-odm/mongo-cxx-driver/cmake -DCMAKE_INSTALL_PREFIX=/home/travis/install -DCMAKE_C_FLAGS="-Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers" -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wno-attributes -Werror -Wno-error=missing-field-initializers" ..

script:
    - make format-lint

    - make all

    # Run bson_mapper tests with catch
    - ./src/bson_mapper/test/test_bson_mapper

    # Run mongo_odm tests with catch
    - ./src/mongo_odm/test/test_mongo_odm

    # Install headers and libs for the examples
    - make install

    # Make the examples
    - make examples

    # Run the examples
    - make run-examples

after-failure:
    - cat /home/travis/build/mongodb/mongo-cxx-odm/build/CMakeFiles/CMakeOutput.log